### ISSUE TITLE
Invalid stage name characters are not stripped out or translated

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#5]
Harness CI requires stage names to meet a specific regex. When converting a Drone pipeline, I noticed at least one stage had characters that were not supported.

```
Error: Invalid yaml: $.pipeline.stages[57].stage.name: does not match the regex pattern ^[a-zA-Z_][-0-9a-zA-Z_\s]{0,127}$
```

We should strip out and/or translate invalid stage name characters during conversion.

**Comment by bradrydzewski** [comment]
I updated the downgrade function to convert names to a slug which strips special characters. This _should_ solve the problem. If not, we'll need to collect some samples of what does / does not work and update our slug function accordingly
https://github.com/drone/go-convert/commit/16ffb71f4efdb12b0e4bc8f67e07d3523874df69#diff-8865ad14716d0f160ef996df47eb1750206588bf431971e39cf3c5042237a769
