### ISSUE TITLE
We shouldn't force identifiers to match names

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#7]
Many pipelines will have pipeline names, stages, steps with names that are compatible with Harness CI's `name` field.

The `identifier` field is more restrictive, so we should keep the current logic that strips invalid characters, but I don't feel the resulting `identifier` field should then also become the `name` field, we should use the original name/stage/step whenever possible.

**Comment by bradrydzewski** [comment]
may not be perfect, but this should be more accurate, and we can have our devs build on this logic to make it more accurate if needed https://github.com/drone/go-convert/commit/fc9ee65743b2149b41e410c9bdadaec5a2b00ad6
