### ISSUE TITLE
[drone] replace `/drone/src` strings with `/harness`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#98]
Drone's default workspace is `/drone/src` https://docs.drone.io/pipeline/docker/syntax/workspace/

Harness CI's default workspace is `/harness`.

After conversion, we should do a string replacement on all `/drone/src` strings with `/harness` before returning the yaml.

**Comment by eoinmcafee00** [comment]
@jimsheldon - can you point me to where in the downgraded yaml / new yaml this can be set? Is it possible this is just a hardcoded location that can be changed?

**Comment by eoinmcafee00** [comment]
Or maybe I've misunderstood and you simply want a find and replace in the yaml for anywhere we see /drone/src to harness?

**Comment by jimsheldon** [comment]
Yes just a find and replace, you got it.

Fix in #100
